name:    Database Mappers
summary: >
    Create a database mapper class for several of the models in your application, and use them
    to manipulate data in the database.
ruberick:
    - "Is the output valid HTML on the form pages and its success message page?"
    - "Does the code execute error-free?"
    - "Is the code free of all debugging statements?"
    - "Does the code contain at least one Mapper class?"
    - "Does the Mapper class contain at least one method for retrieving entities?"
    - "Does the Mapper class convert database results into their object entities in the code?"
    - "Is the Mapper class used on at least one HTML page to produce output?"
    - > "All entity mapper classes must use your entity classes.  
        When retrieving data, they must return entity objects (an array or single object), 
        and when accepting data to insert or update, they must use entity objects as parameters"